/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;
import objetos.*;
import main.*;

/**
 *
 * @author YARITZA
 */
public class Inicio_medico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inicio_medico.class.getName());
   Funciones a = Funciones.getInstancia();
    /**
     * Creates new form Inicio_medico
     */
    public Inicio_medico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boton_inicio_medico = new javax.swing.JButton();
        tx_inicio_cedula_medico = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_inicio_medico.setText("Iniciar seccion");
        boton_inicio_medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_inicio_medicoActionPerformed(evt);
            }
        });
        jPanel1.add(boton_inicio_medico, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        tx_inicio_cedula_medico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_inicio_cedula_medicoActionPerformed(evt);
            }
        });
        tx_inicio_cedula_medico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tx_inicio_cedula_medicoKeyTyped(evt);
            }
        });
        jPanel1.add(tx_inicio_cedula_medico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 260, 40));

        jLabel1.setText("ingrese cedula");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 90, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setText("medico");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cruz.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 440));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo_Medico_entrgar_receta.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_inicio_medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_inicio_medicoActionPerformed
     if(tx_inicio_cedula_medico.getText().trim().isEmpty()){

    javax.swing.JOptionPane.showMessageDialog(null, "Ingrese la cedula");

}else{

    boolean existe = false;

    for(int i = 0; i < a.getDoctores().size(); i++){

        if(a.getDoctores().get(i).getCedula().equals(tx_inicio_cedula_medico.getText())){

            existe = true;

            Medico m = new Medico();
            m.setVisible(true);
            dispose();

        }

    }

    if(existe == false){

        javax.swing.JOptionPane.showMessageDialog(null, "Medico no encontrado");

    }

}      // TODO add your handling code here:
    }//GEN-LAST:event_boton_inicio_medicoActionPerformed

    private void tx_inicio_cedula_medicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tx_inicio_cedula_medicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_inicio_cedula_medicoActionPerformed

    private void tx_inicio_cedula_medicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_inicio_cedula_medicoKeyTyped
char c=evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.consume();
            javax.swing.JOptionPane.showMessageDialog(null,"Solo puede digitar numeros");
            
        }             // TODO add your handling code here:
    }//GEN-LAST:event_tx_inicio_cedula_medicoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Inicio_medico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_inicio_medico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tx_inicio_cedula_medico;
    // End of variables declaration//GEN-END:variables
}
