/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;
import main.*;
import objetos.*;
/**
 *
 * @author YARITZA
 */
public class Registro extends javax.swing.JFrame {
    
    Funciones a = Funciones.getInstancia();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registro.class.getName());
    
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tx_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tx_edad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tx_cedula = new javax.swing.JTextField();
        B_registro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        error_registro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel2PropertyChange(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 150, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 90));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 50, 30));
        jPanel1.add(tx_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 220, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Edad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 50, 30));

        tx_edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tx_edadKeyTyped(evt);
            }
        });
        jPanel1.add(tx_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 220, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Cedula");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 50, 30));

        tx_cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tx_cedulaKeyTyped(evt);
            }
        });
        jPanel1.add(tx_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 220, 30));

        B_registro.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        B_registro.setText("Registrar");
        B_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_registroActionPerformed(evt);
            }
        });
        jPanel1.add(B_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 130, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cruz.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 340, 390));
        jPanel1.add(error_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 180, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel2PropertyChange
        // TODO add your handling code here
    }//GEN-LAST:event_jPanel2PropertyChange

    private void B_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_registroActionPerformed

      // CORRECCIÓN: Usamos .trim() para limpiar espacios vacíos accidentales
        String nombre = tx_nombre.getText().trim();
        String vedad = tx_edad.getText().trim();
        String cedula = tx_cedula.getText().trim();
        
        error_registro.setText("");
        
        if (nombre.isEmpty() || vedad.isEmpty() || cedula.isEmpty()) {
            error_registro.setText("Algun espacio esta en blanco");
        } else if (cedula.length() < 8 || cedula.length() > 10) {
            error_registro.setText("La cedula debe tener de 8 a 10 digitos");
        } else {
            try {
                int edad = Integer.parseInt(vedad);
                
                // Registra en la instancia única del Singleton
                a.registrarPaciente(new Paciente(cedula, nombre, edad));
                
                // Redirección limpia
                new usuario().setVisible(true);
                this.setVisible(false);
            } catch (NumberFormatException e) {
                error_registro.setText("La edad debe ser un número válido.");
            }
        }  
 

    

    }//GEN-LAST:event_B_registroActionPerformed

    private void tx_edadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_edadKeyTyped
 
        char c=evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.consume();
            javax.swing.JOptionPane.showMessageDialog(null,"Solo puede digitar numeros");
            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tx_edadKeyTyped

    private void tx_cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tx_cedulaKeyTyped

        char c=evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.consume();
            javax.swing.JOptionPane.showMessageDialog(null,"Solo puede digitar numeros");
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tx_cedulaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_registro;
    private javax.swing.JLabel error_registro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tx_cedula;
    private javax.swing.JTextField tx_edad;
    private javax.swing.JTextField tx_nombre;
    // End of variables declaration//GEN-END:variables
}
