/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;
import main.*;
import objetos.*;


/**
 *
 * @author ACER
 */
public class vista_usuario extends javax.swing.JFrame {
    
    Funciones a = Funciones.getInstancia();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(vista_usuario.class.getName());

    private Paciente pacienteActual;
    /**
     * Creates new form vista_usuario
     */
    public vista_usuario(Paciente paciente) {
        this.pacienteActual = paciente;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        B_agendar_cardiologia = new javax.swing.JToggleButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        txt_area_cardiologia = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        B_agendar_dermatologia = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_area_dermatologia = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        B_agendar_pediatria = new javax.swing.JToggleButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_area_pediatria = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        B_agendar_citaGeneral = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area_citaGeneral = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));

        jPanel15.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 490));

        jPanel3.setBackground(new java.awt.Color(51, 204, 255));

        jPanel16.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("VITALCORE");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo pequeño.png"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo pequeño.png"))); // NOI18N

        jButton2.setText("x");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel7)
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addComponent(jLabel20)
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(4, 4, 4)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 660, 100));
        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));
        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));
        jPanel1.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jTabbedPane4.setBackground(new java.awt.Color(51, 204, 255));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B_agendar_cardiologia.setText("AGENDAR CITA");
        B_agendar_cardiologia.addActionListener(this::B_agendar_cardiologiaActionPerformed);
        jPanel8.add(B_agendar_cardiologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        txt_area_cardiologia.setColumns(20);
        txt_area_cardiologia.setRows(5);
        jScrollPane9.setViewportView(txt_area_cardiologia);

        jPanel8.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 250, 100));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel19.setText("MOTIVO DE LA CITA: ");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pngtree-background-of-operation-room-in-hospital-health-care-concept-image_15733972.jpg"))); // NOI18N
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 330));

        jTabbedPane4.addTab("CARDIOLOGIA", jPanel8);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B_agendar_dermatologia.setText("AGENDAR CITA");
        B_agendar_dermatologia.addActionListener(this::B_agendar_dermatologiaActionPerformed);
        jPanel11.add(B_agendar_dermatologia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        txt_area_dermatologia.setColumns(20);
        txt_area_dermatologia.setRows(5);
        jScrollPane2.setViewportView(txt_area_dermatologia);

        jPanel11.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 250, 110));

        jLabel5.setText("MOTIVO DE LA CITA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPanel11.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dermatologia-cosmetica.png"))); // NOI18N
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 330));

        jTabbedPane4.addTab("DERMATOLOGIA", jPanel11);

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B_agendar_pediatria.setText("AGENDAR CITA");
        B_agendar_pediatria.addActionListener(this::B_agendar_pediatriaActionPerformed);
        jPanel13.add(B_agendar_pediatria, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        txt_area_pediatria.setColumns(20);
        txt_area_pediatria.setRows(5);
        jScrollPane5.setViewportView(txt_area_pediatria);

        jPanel13.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 260, 120));

        jLabel8.setText("MOTIVO DE LA CITA");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jPanel13.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pediatra-1080-×-615-px.jpg"))); // NOI18N
        jPanel13.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 630, 340));

        jTabbedPane4.addTab("PEDIATRIA", jPanel13);

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B_agendar_citaGeneral.setText("AGENDAR CITA");
        B_agendar_citaGeneral.addActionListener(this::B_agendar_citaGeneralActionPerformed);
        jPanel7.add(B_agendar_citaGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        txt_area_citaGeneral.setColumns(20);
        txt_area_citaGeneral.setRows(5);
        jScrollPane1.setViewportView(txt_area_citaGeneral);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 290, 150));

        jLabel2.setText("MOTIVA DE LA CITA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Adsiz-tasarim-29.png"))); // NOI18N
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 334));

        jTabbedPane4.addTab("CITA GENERAL", jPanel7);

        jPanel1.add(jTabbedPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 630, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_agendar_pediatriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_agendar_pediatriaActionPerformed
                                                 
    String motivo = txt_area_pediatria.getText().trim();
    
    // 1. Validar que el usuario haya escrito el motivo
    if (motivo.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, digite el motivo de la cita para Pediatría.");
        return;
    }

    // 2. Buscar un doctor cuya especialidad (tipo) sea "pediatra"
    Doctor doc = a.buscarDoctorPorEspecialidad("pediatra");
    
    // Si no encuentra ningún pediatra asignado, le pone una cédula genérica de respaldo
    String cedulaDoc = (doc != null) ? doc.getCedula() : "40405050"; 

    // 3. Generar un ID único para la consulta
    String idConsulta = "C" + (a.getPacientes().size() + System.currentTimeMillis() % 1000); 

    // 4. Crear el objeto Consulta
    Consulta nuevaConsulta = new Consulta(idConsulta, "27/05/2026", "02:00 PM", pacienteActual.getCedula(), cedulaDoc, motivo, false);

    // 5. Guardar los datos en el sistema
    a.registrarConsulta(nuevaConsulta);
    
    // 6. Mensaje de éxito y limpiar el componente
    javax.swing.JOptionPane.showMessageDialog(this, "¡Cita de Pediatría agendada con éxito!");
    txt_area_pediatria.setText("");
    }//GEN-LAST:event_B_agendar_pediatriaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new usuario().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void B_agendar_dermatologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_agendar_dermatologiaActionPerformed
    String motivo = txt_area_dermatologia.getText().trim();
    if (motivo.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, digite el motivo de la cita.");
        return;
    }

    Doctor doc = a.buscarDoctorPorEspecialidad("dermatologo");
    String cedulaDoc = (doc != null) ? doc.getCedula() : "20212343";

    String idConsulta = "C" + (a.getPacientes().size() + System.currentTimeMillis() % 1000);
    Consulta nuevaConsulta = new Consulta(idConsulta, "25/05/2026", "10:00 AM", pacienteActual.getCedula(), cedulaDoc, motivo, false);

    a.registrarConsulta(nuevaConsulta);
    javax.swing.JOptionPane.showMessageDialog(this, "¡Cita de Dermatología agendada con éxito!");
    txt_area_dermatologia.setText("");
    }//GEN-LAST:event_B_agendar_dermatologiaActionPerformed

    private void B_agendar_citaGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_agendar_citaGeneralActionPerformed
     String motivo = txt_area_citaGeneral.getText().trim();
    if (motivo.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, digite el motivo de la cita.");
        return;
    }

    
    Doctor doc = a.buscarDoctorPorEspecialidad("general");
    String cedulaDoc = (doc != null) ? doc.getCedula() : "2014223"; // ID por defecto por si acaso

 
    String idConsulta = "C" + (a.getPacientes().size() + System.currentTimeMillis() % 1000); 
    Consulta nuevaConsulta = new Consulta(idConsulta, "24/05/2026", "08:00 AM", pacienteActual.getCedula(), cedulaDoc, motivo, false);

    a.registrarConsulta(nuevaConsulta);
    javax.swing.JOptionPane.showMessageDialog(this, "¡Cita de Medicina General agendada con éxito!");
    txt_area_citaGeneral.setText(""); 
    }//GEN-LAST:event_B_agendar_citaGeneralActionPerformed

    private void B_agendar_cardiologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_agendar_cardiologiaActionPerformed
      String motivo = txt_area_cardiologia.getText().trim();
    
    
    if (motivo.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, digite el motivo de la cita para Cardiología.");
        return;
    }

  
    Doctor doc = a.buscarDoctorPorEspecialidad("cardiologo");
    
    
    String cedulaDoc = (doc != null) ? doc.getCedula() : "30304040"; 

   
    String idConsulta = "C" + (a.getPacientes().size() + System.currentTimeMillis() % 1000); 

    
    Consulta nuevaConsulta = new Consulta(idConsulta, "26/05/2026", "09:30 AM", pacienteActual.getCedula(), cedulaDoc, motivo, false);

 
    a.registrarConsulta(nuevaConsulta);
    
    javax.swing.JOptionPane.showMessageDialog(this, "¡Cita de Cardiología agendada con éxito!");
    txt_area_cardiologia.setText("");
    }//GEN-LAST:event_B_agendar_cardiologiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new vista_usuario(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton B_agendar_cardiologia;
    private javax.swing.JToggleButton B_agendar_citaGeneral;
    private javax.swing.JButton B_agendar_dermatologia;
    private javax.swing.JToggleButton B_agendar_pediatria;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextArea txt_area_cardiologia;
    private javax.swing.JTextArea txt_area_citaGeneral;
    private javax.swing.JTextArea txt_area_dermatologia;
    private javax.swing.JTextArea txt_area_pediatria;
    // End of variables declaration//GEN-END:variables
}
